### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by therealrobster** [eigenmiao/Rickrack#17]
### Description

Hi there,

I installed from the .DEB file on the latest build.

I get the following on load:

Rickrack[202350]: segfault at 6c98038 ip 00007fda1d6b908d sp 00007ffc6eed9bf0 error 4 in libxkbcommon-x11.so.0.0.0[7fda1d6b8000+4000] likely on CPU 1 (core 1, socket 0)
Apr 06 14:27:01 carbonx1 kernel: Code: 0f 84 b9 00 00 00 48 83 c3 01 48 39 5c 24 08 0f 84 33 02 00 00 48 8b 04 24 48 21 d8 74 e8 49 8b 14 24 48 8d 0c 85 00 00 00 00 <44> 8b 3c 82 45 85 ff 75 aa 45 8b 7c 24 18 41 8b 44 24 1c 41 8d 57

This is from checking system logs.

```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    CPU family:          6
    Model:               142
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            10
    CPU max MHz:         4000.0000
    CPU min MHz:         400.0000

```
Running POPOS 22.04 LTS.

I hope that helps, would love to use this software :-)

### Reproduction steps

```bash
Install via DEB file, then run
```

### Logs

```bash
Rickrack[202350]: segfault at 6c98038 ip 00007fda1d6b908d sp 00007ffc6eed9bf0 error 4 in libxkbcommon-x11.so.0.0.0[7fda1d6b8000+4000] likely on CPU 1 (core 1, socket 0)
Apr 06 14:27:01 carbonx1 kernel: Code: 0f 84 b9 00 00 00 48 83 c3 01 48 39 5c 24 08 0f 84 33 02 00 00 48 8b 04 24 48 21 d8 74 e8 49 8b 14 24 48 8d 0c 85 00 00 00 00 <44> 8b 3c 82 45 85 ff 75 aa 45 8b 7c 24 18 41 8b 44 24 1c 41 8d 57
```

### OS

Linux

### Preferences

- [ ] If possible, I would like to fix this.

**Comment by eigenmiao** [comment]
Thanks for your feedback. It seems that PySide2 does not work well on both PopOS and Ubuntu. [Rickrack v2.7.23](https://github.com/eigenmiao/Rickrack/releases/download/v2.7.23-pre/Rickrack_v2.7.23_pre_en_linux_x86_64.deb) is compiled with PyQt5 and can run normally on PopOS. I will consider switching back to PyQt5 for the next version.

If you want to use Rickrack on Linux, it's better to try  [Rickrack v2.7.23](https://github.com/eigenmiao/Rickrack/releases/download/v2.7.23-pre/Rickrack_v2.7.23_pre_en_linux_x86_64.deb) first, and then wait for the next version update.

Remember to uninstall Rickrack v2.7.25 before installing Rickrack v2.7.23, use the command “sudo dpkg -P Rickrack”.

<img width="641" alt="pop" src="https://user-images.githubusercontent.com/59333735/230544153-0dabb9e5-158b-4ae6-9f72-13ee0b6a7f50.png">

**Comment by therealrobster** [comment]
Thank you for your detailed response.  I removed, then installed 2.7.23 and it's working!  Thanks for your time and I hope my bug report helps.

Interestingly, I thought it was perhaps still broken, but it took nearly a whole minute to load to the interface.  I don't mind, now that I know. :-)

**Comment by eigenmiao** [comment]
Yes, I noticed that Rickrack still had some error output when running it on PopOS. But at least it works. I don't plan to further optimize the running speed in the near future, it's too time-consuming. :smile_cat:

**Comment by therealrobster** [comment]
Totally understand!
