### ISSUE TITLE
mac端hidpi适配 / mac 默认字体与系统语言不一致（hidpi adaptation on mac / default font）

### ISSUE THREAD

**Issue by Githubcatone** [eigenmiao/Rickrack#18]
### Summary

mac端貌似没有适配hidpi？整个界面都是模糊的

### Basic Example

<img width="632" alt="截屏2023-04-09 13 52 04" src="https://user-images.githubusercontent.com/53322927/230756833-79e7f7e3-8127-4653-9238-be0962dfe75b.png">

### Preferences

- [ ] If possible, I would like to implement this.

**Comment by eigenmiao** [comment]
我手头没有 mac 电脑，所以我没办法为 mac 系统做微调。我在代码里加入了启用高 dpi 缩放的代码，并且在 Windows 上表现良好。可能 macOS 启用高 dpi 缩放的方式跟 Windows 不太一样？

<img width="467" alt="win" src="https://user-images.githubusercontent.com/59333735/230759610-23aa67ae-b834-41aa-a6e6-dfc202136420.png">

**Comment by eigenmiao** [comment]
我对 mac 系统不是很熟悉，可以问下你是在系统中对软件单独设置了缩放吗？

**Comment by eigenmiao** [comment]
如果是字体太小，不建议从系统层面直接对软件设置缩放，而是在软件设置中设置字体大小。
字体大小的设置方法：https://github.com/eigenmiao/Rickrack/issues/14

* 10 号字体：
![before](https://user-images.githubusercontent.com/59333735/230782051-0c914b51-0f3a-4560-a385-03153a39a269.png)

* 16 号字体：
![after](https://user-images.githubusercontent.com/59333735/230782061-0a3bfbf7-a78b-4b64-85b9-20283270a73a.png)

**Comment by Githubcatone** [comment]
没有在系统层面进行软件缩放，设置字体大小并不起作用
<img width="630" alt="截屏2023-04-10 10 05 20" src="https://user-images.githubusercontent.com/53322927/230811151-168ac67c-3984-492a-bb1c-2b9f709bdf49.png">
<img width="355" alt="截屏2023-04-10 10 05 37" src="https://user-images.githubusercontent.com/53322927/230811156-a80e4347-3f15-403c-88e1-203a9e84c8d4.png">

**Comment by eigenmiao** [comment]
那我就不清楚是什么原因了。我这里没有 mac 设备，没办法复现这个字体模糊的问题。看后期有没有用 mac 的大佬愿意帮忙做一下适配吧。

**Comment by eigenmiao** [comment]
This software written using PyQt5 version 5.12.1 has a problem with blurred fonts on the mac platform. If anyone sees this issue and wants to help out, please submit a PR directly. Thanks.

This issue has been reopened for a solution.

这个使用 PyQt5 5.12.1 版本编写的软件在 mac 平台上出现了字体模糊的问题。如果有人看到这个问题，愿意帮助解决，请直接提交 PR。谢谢。

此问题已重新打开以寻求解决方案。

**Comment by eigenmiao** [comment]
This software written using PyQt5 version 5.12.1 has a problem with blurred fonts on the mac platform. If anyone sees this issue and wants to help out, please submit a PR directly. Thanks.

This issue has been reopened for a solution.

这个使用 PyQt5 5.12.1 版本编写的软件在 mac 平台上出现了字体模糊的问题。如果有人看到这个问题，愿意帮助解决，请直接提交 PR。谢谢。

此问题已重新打开以寻求解决方案。

**Comment by eigenmiao** [comment]
macOS 上字体模糊的问题解决了。默认语言的问题也解决了。macOS 上获取的语言是“None”，然后就重定向到“挪威语（no）”上面去了。

The issue of font blur on macOS has been resolved. The issue of default language has also been resolved. The language obtained on macOS is "None" and then redirected to "Norwegian (no)".

修改前：
<img width="800" alt="before_flur" src="https://user-images.githubusercontent.com/59333735/232033908-4d435f43-e7d7-433e-a83b-8aaab45c8277.png">

修改后：
<img width="800" alt="after_flur" src="https://user-images.githubusercontent.com/59333735/232033943-9a7714ec-86cc-4ec4-af27-3c8f8676f534.png">

**Comment by eigenmiao** [comment]
重新编译的 mac 版本：https://github.com/eigenmiao/Rickrack/releases/download/v2.7.26/Rickrack_v2.7.26_zh_darwin_x86_64.dmg
