### ISSUE TITLE
macbook 安装完2.8.41版本闪退

### ISSUE THREAD

**Issue by tsaoshuang** [eigenmiao/Rickrack#30]
macbook 安装完2.8.41版本闪退

**Comment by eigenmiao** [comment]
你好，你用的是什么版本的 macOS 呢，处理器是 M2 芯片吗？

**Comment by eigenmiao** [comment]
已重新编译：https://github.com/eigenmiao/Rickrack/releases/tag/v2.8.41.1

**Comment by eigenmiao** [comment]
如果没有其他问题，我就把这个 issue 关闭了
