### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by TMaHM** [eigenmiao/Rickrack#35]
Win11系统
通过winget install rickrack命令安装

之后运行报错Failed to execute script main

![image](https://github.com/eigenmiao/Rickrack/assets/33696238/09d6bbf9-8b67-40f8-9771-a606112436af)

请问该如何解决这个问题，或者需要我提供其他的信息？

设备名称	StephenHomework
处理器	13th Gen Intel(R) Core(TM) i5-13600KF   3.50 GHz
机带 RAM	64.0 GB (63.8 GB 可用)
设备 ID	F948E696-9799-44E9-98F5-39E93CD92DBC
产品 ID	00331-10000-00001-AA411
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 11 专业版
版本	22H2
安装日期	‎4/‎15/‎2023
操作系统版本	22621.2861
体验	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by eigenmiao** [comment]
你试试在安装目录（默认目录在```C:\Program Files\Rickrack```）里新建一个```settings.json```文件，内容为：
```
{"store_loc": false, "lang": "zh"}
```
之前打包安装包时忘记添加进去了。如果可行的话，下个版本我将修复这个问题。

**Comment by eigenmiao** [comment]
此外，你可以试试绿色免安装版本，避免在 C 盘安装软件导致的权限问题：https://github.com/eigenmiao/Rickrack/releases/download/v2.8.41/Rickrack_v2.8.41_zh_windows_AMD64.zip

祝好

**Comment by TMaHM** [comment]
谢谢，问题解决了 👍😁
