### ISSUE TITLE
Missing support for NixOS based systems

### ISSUE THREAD

**Issue by CarlosCraveiro** [eigenmiao/Rickrack#36]
Currently NixOS support for snaps is quite limited, as is the manual installation of a package as would be done in imperative Linux distributions such as Fedora, Debian, Ubuntu, CentOS and Arch, which complicates the life of Rickrack's users on NixOS. 

Therefore, as a Rickrack user on NixOS I would really appreciate if Rickrack were available for download through the distribution's official repository, the [nixpkgs](https://github.com/NixOS/nixpkgs). I even offer to write the Rickrack recipe for nixpkgs, but I need help on the step-by-step process to build the application from source code.

Just in case you haven't heard about NixOS before, here's a brief and informative description:
> [NixOS](https://nixos.org/) is a Linux distribution based on the [Nix](https://nixos.wiki/wiki/Nix) package manager and build system. It supports [reproducible](https://reproducible-builds.org/) and [declarative](https://en.wikipedia.org/wiki/Declarative_programming) system-wide [configuration management](https://en.wikipedia.org/wiki/Configuration_management) as well as [atomic](https://en.wikipedia.org/wiki/Atomicity_(database_systems)) upgrades and rollbacks, although it can additionally support [imperative](https://en.wikipedia.org/wiki/Imperative_programming) package and user management. In NixOS, all components of the distribution — including the [kernel](https://en.wikipedia.org/wiki/Linux_kernel), installed [packages](https://en.wikipedia.org/wiki/Package_manager) and system configuration files — are built by [Nix](https://nixos.wiki/wiki/Nix) from [pure functions](https://en.wikipedia.org/wiki/Pure_function) called [Nix expressions](https://nixos.wiki/wiki/Nix_Expression_Language).
Extracted from https://nixos.wiki/wiki/Overview_of_the_NixOS_Linux_distribution

**Comment by eigenmiao** [comment]
Thank you for your interest in Rickrack and willingness to create a dedicated installation package for NixOS.

1. Rickrack provides pre-compiled executable files that can run directly on Linux platforms (x64, X11 desktop environment). The pre-compiled executable files can be downloaded [here](https://github.com/eigenmiao/Rickrack/releases/download/v2.8.42/Rickrack_v2.8.42_en_linux_x86_64.tar.gz). Perhaps you can use these files to create the nixpkgs package. In fact, I use this method when creating the snap package, and the configuration of the snap package is provided [here](https://github.com/eigenmiao/Rickrack/blob/main/snap/snapcraft.yaml) for reference.

2. If you want to compile from the source code, the compilation method is as follows:
```bash
# Python 3.6

pip install PyQt5==5.15.6
pip install fbs numpy lxml swatch Pillow

git clone https://github.com/eigenmiao/Rickrack
cd Rickrack

fbs freeze
```
The compiled executable files are located in the `target` folder.

**Comment by CarlosCraveiro** [comment]
Thank you very much for the help! I'm now trying to create the Installation package. Going through some problems, but I'll keep trying. I'll send a message here when I have news.

**Comment by eigenmiao** [comment]
Perhaps you can try the portable version first to see if it can run directly (https://github.com/eigenmiao/Rickrack/releases/download/v2.8.42/Rickrack_v2.8.42_en_linux_x86_64.tar.gz). Looking forward to your good news. :)
