### ISSUE TITLE
Change UI box sizes

### ISSUE THREAD

**Issue by gerroon** [eigenmiao/Rickrack#37]
Hi

Thanks for this app. It looks great, but one thing that can be helpful is a way to increase the screen estate. It could be helpful to ffer an option to resize those boxes for more screen estate, it feels like most stuff are burried in scrolling.

thanks

**Comment by eigenmiao** [comment]
Thanks for your advice. The interface will be updated in the next version. In the new interface, option boxes can be collapsed.
![1 png](https://github.com/eigenmiao/Rickrack/assets/59333735/81408e22-ab70-4c0b-bd09-bac5fcf87b03)
