### ISSUE TITLE
保存后,再次打开,没法恢复之前的保存状态哦.

### ISSUE THREAD

**Issue by jinyuanqing** [eigenmiao/Rickrack#8]
### Description

保存后,再次打开,没法恢复之前的保存状态哦.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Preferences

- [ ] If possible, I would like to fix this.

**Comment by eigenmiao** [comment]
你是用的什么系统，哪个版本的软件。我自己测试是可以自动保存和恢复的。
